# Generated by Django 3.2.6 on 2021-08-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210828_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='post_by',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
