# Generated by Django 3.2.6 on 2021-08-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_addbook_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addbook',
        ),
    ]
