# Generated by Django 3.2.6 on 2021-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_addbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
