# Generated by Django 3.2.6 on 2021-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_addbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
